### ISSUE TITLE
Add visuals & screenshots

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/label-printing#27]
including localised screenshots (because it shows UI elements)
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#banner-filenames

```[tasklist]
### Tasks
- [ ] Normal Banner: `banner-772x250.(jpg|png)`
- [ ] Normal Banner (Localized): `banner-772x250-(rtl|es|es_ES).(jpg|png)`
- [ ] High-DPI (Retina): `banner-1544x500.(jpg|png)`
- [ ] High-DPI (Retina Localized): `banner-1544x500-(rtl|es|es_ES).(jpg|png)`
- [ ] Normal: `icon-128x128.(png|jpg)`
- [ ] High-DPI (Retina): `icon-256x256.(png|jpg)`
- [ ] SVG: `icon.svg`
- [ ] `screenshot-1.(png|jpg)` Insert the Label Printing block
- [x] `screenshot-1-de.(png|jpg)`
- [ ] `screenshot-2.(png|jpg)` Choose your pre-defined Label
- [x] `screenshot-2-de.(png|jpg)`
- [ ] `screenshot-3.(png|jpg)` Switch visually between different label presets
- [x] `screenshot-3-de.(png|jpg)`
- [ ] `screenshot-4.(png|jpg)` Fill in your label content
- [x] `screenshot-4-de.(png|jpg)`
- [ ] `screenshot-5.(png|jpg)` Check in your browsers print dialog ...
- [x] `screenshot-5-de.(png|jpg)`
```
