### ISSUE TITLE
Add CRUD UI for labels

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/label-printing#5]
Currently the creation of new labels is only possible via code.

Even the *patterns* including *synced-patterns*, already have a UI, we need to find a way to capture our different meta-data. This is currently saved as one post_meta array holding all the data.
```[tasklist]
### Tasks
- [ ] Create a new admin-only block to manage a Label
- [ ] Let the block CRUD all relevant post_meta
- [ ] Let the block keep the template, that is currently static for all labels
- [ ] Allow to set custom inner safe distance (currently 10%)
```
