### ISSUE TITLE
Submit to wp.org/plugins

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/label-printing#6]
```[tasklist]
### Tasks
- [ ] Update readme to follow the Standards at https://wordpress.org/plugins/readme.txt
- [x] Validate readme with https://wpreadme.com/
- [x] Check that we followed all block guidelines at https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md
- [ ] Validate plugin using the https://wordpress.org/plugins/developers/block-plugin-validator/
- [x] Run ~~https://wordpress.org/plugins/plugin-check/~~ https://github.com/swissspidy/wp-plugin-check-action@main without failure
- [ ] https://github.com/figuren-theater/label-printing/issues/27
- [x] Submit for Review https://wordpress.org/plugins/developers/add/
- [ ] ***Warning:*** The "Short Description" section is too long and was truncated. A maximum of 150 characters is supported.
- [ ] Get plugin approved
- [ ] Opt-in for the *community* plugins-taxonomy
- [ ] Opt-in for the *blocks* taxonomy, see https://developer.wordpress.org/plugins/wordpress-org/add-your-plugin-to-the-block-directory/
- [ ] #7
- [ ] > Go to https://wordpress.org/support/plugin/YOURPLUGIN and look at the sidebar on the right. Click the Subscribe to this Plugin button for email alerts.
```

**Comment by carstingaxion** [comment]
First time running https://wordpress.org/plugins/plugin-check/ (on the dev folder)
![grafik](https://github.com/figuren-theater/label-printing/assets/198883/c312cd6a-05bb-4331-8537-4850d0f8a1e1)

**Comment by carstingaxion** [comment]
![IMG_0172](https://github.com/figuren-theater/label-printing/assets/198883/cac29ed2-55eb-4f1a-8a86-14dfc6c155e4)

**Comment by carstingaxion** [comment]
![image](https://github.com/figuren-theater/label-printing/assets/198883/bf4aeb9e-1709-450d-9ecd-6e62133ace30)

**Comment by carstingaxion** [comment]
1. [Uploaded a nice .zip](https://github.com/figuren-theater/label-printing/actions/runs/9282860186/job/25541786799)
2. Testing [0.3.1/label-printing.zip](https://github.com/figuren-theater/label-printing/releases/download/0.3.1/label-printing.zip) with https://wordpress.org/plugins/developers/block-plugin-validator/
3. ![grafik](https://github.com/figuren-theater/label-printing/assets/198883/1ee31c75-bfd8-4c7f-9524-35cad6549db8)

**Comment by carstingaxion** [comment]
1. ![grafik](https://github.com/figuren-theater/label-printing/assets/198883/a7e74ecf-b128-4973-907b-1c6b44fdc26f)
2. ![grafik](https://github.com/figuren-theater/label-printing/assets/198883/fba41b10-cc59-4561-b1fe-7d8d01e1f518)
3. https://github.com/figuren-theater/label-printing/pull/51
4. ![grafik](https://github.com/figuren-theater/label-printing/assets/198883/4d42168d-8938-4aa0-a454-a1b6a5f7c910)
5. [playground.wordpress](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fwordpress.org%2Fplugins%2Fwp-json%2Fplugins%2Fv1%2Fplugin%2Flabel-printing%2Fblueprint.json%3Fzip_hash%3D5dd91a719e75311da501d453c954d714%26type%3Dpcp)
6. ![grafik](https://github.com/figuren-theater/label-printing/assets/198883/6fa4a997-174a-452d-b73f-8f287268784e)

**Comment by carstingaxion** [comment]
![grafik](https://github.com/figuren-theater/label-printing/assets/198883/4678c4f9-5cc0-4db5-a694-f8a35ca44da6)

![grafik](https://github.com/figuren-theater/label-printing/assets/198883/f5273ccd-f3f9-4db4-9f32-15de12f1fed7)

**Comment by carstingaxion** [comment]
![grafik](https://github.com/figuren-theater/label-printing/assets/198883/715b398b-8750-45e3-9e60-bfbcc19bf73f)
